- name: catalouge configurations
  hosts: catalogue
  connection: local


  tasks:
  - name: Disable the current module of nodejs
    ansible.builtin.dnf:
      name: nodejs
      module_state: reset
    changed_when: true # This operation always reports changed

  - name: Enable nodejs:20 module stream
    ansible.builtin.dnf:
      name: nodejs:20
      module_state: enabled
      state: present