- name: catalouge configurations
  hosts: catalogue
  become: yes

  tasks:
  - name: Enable nodejs:20                                        # we dont have option to enable the secific version of nodejs in dnf module s we are using command module and we are not doing reirection or pipeing so thats why we are not using shell
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: creating the system user roboshop
    ansible.builtin.user: 
      name: roboshop
      system: true #system user 
      home: /app #optionally setting home
      shell: /sbin/nologin
      comment: roboshop system user


  - name: delete app directory    # why we are deleting the directory because if you running the code/play/script meanas there are code changes right or you redeplying the play  if code already existed ansible will skip if you run the play so that why we are deleting.
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Downloading the catalogue code
    ansible.builtin.get_url: 
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

  - name: Unzip the code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes # what is remote here: catalogue not ansible and we've already downloaded the app code above cmd "get_url" so that why we need to mention remote_src: yes otherwise you wll get error if you remove this one 

  - name: Install the dependencies
    community.general.npm:
      path: /app # Directory containing package.json
      state: present

  - name: copy the catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install MongoDB Client Package
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: Check products loaded or not
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: Load the data
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js #comand module will not work because  we are doing redrection
    when: catalogue_output.stdout | int < 0  # before catalogue_output.stdout<0 we cant compare string with number so i converted string to integer using pipe


  - name: Start or enable catalogue with daemon-reload
    ansible.builtin.systemd:
      name: catalogue
      daemon_reload: yes
      state: started
      enabled: yes
      


  

  
  
  