- name: frontend configuration
  hosts: frontend
  become: yes

  tasks:
    - name: enable nginx 1.24
      ansible.builtin.command: dnf module enable nginx:1.24 -y

    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Remove the nginx default directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Recreate the nginx directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Remove the frontend code
      ansible.builtin.file:
        path: /tmp/frontend.zip
        state: absent

    - name: Download the frontend code
      ansible.builtin.get_url:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /tmp/frontend.zip

    - name: Unarchive the frontend code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Remove the nginx default
      ansible.builtin.file:
        path: /etc/nginx/nginx.conf
        state: absent

    - name: copy the service file
      ansible.builtin.template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Start, enabled the nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes
