# download py library botocore and boto3 becoz ansible develoed in python ;  in background python code will execute 
# pip3.9 install botocore boto3

- name : create ec2 and route53 records
  hosts: all
  connection: local

  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-0b1f7c3d25067bf9a
    subnet_id: subnet-0bb417478919bf408
    env: dev
    zone_id: Z07326442Z8C3IRLJ3030
    domain_name: cloudkarna.in
    action: create
    instances:
    - dynamodb
    - catalogue
    - mongodb

  tasks:
  ##CREATE
  - name: Launching AWS instance
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      image_id: "{{ ami_id }}" # Replace with a valid AMI ID
      region: us-east-1
      security_group: "{{ sg_id }}"
      state: present
      vpc_subnet_id: "{{ subnet_id }}"
      tags:
        Name: "{{ item }}-{{ env }}"
        project: roboshop
        component: "{{ item }}"
        env: "{{ env }}"     
    loop: "{{ instances }}"
    register: ec2_info
    when: action == "create"
  
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"
    when: action == "create"

  - name: Create a new A record in Route53
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"  #cloudkarna.in
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" #dynamodb-dev.cloudkarna.in, frontend-dev.cloudkarna.in
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
      wait: false
    loop: "{{ ec2_info.results }}"  #list
    when: action == "create"


  - name: Create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}" #cloudkarna.in
      record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.cloudkarna.in
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
      wait: false

    loop: "{{ ec2_info.results }}" #list
    when: # and
    - item.item == "frontend"
    - action == "create"


  ##DELETE
  - name: Delete r53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}" #cloudkarna.in
      record: "{{ item }}-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1

    loop: "{{ instances }}"
    when: action == "destroy"


  - name: Delete AWS instances
    amazon.aws.ec2_instance:
      state: absent
      filters:
        "tag:Name": "{{ item }}-{{ env }}"
        "tag:project": roboshop
        "tag:component": "{{ item }}"
    loop: "{{ instances }}"
    when: action == "destroy"


#Route53 tasks don’t need instance identification beyond record name.
#EC2 deletion must know which instance(s) to terminate → filters/instance IDs required.