- name : Instance and route53 creation
  hosts: all
  connection: local

  become: yes
  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    SG_ID: "sg-0b1f7c3d25067bf9a"
    SUBNET_ID: "subnet-0bb417478919bf408"
    env: "dev"
    ZONE_ID: "Z07326442Z8C3IRLJ3030"
    DOMAIN_NAME: "cloudkarna.in"
    Instances:
      - dynamodb
      - cart

  tasks:
  - name: Instance creation
    amazon.aws.ec2_instance: 
      instance_type: "t3.micro"
      image_id: "{{ami_id}}"
      region: "us-east-1"
      security_group: "{{SG_ID}}"
      vpc_subnet_id: "{{SUBNET_ID}}"
      tags:
        project: roboshop
        component: "{{item}}"
        Environment: "{{env}}"
        name: "{item}}-{{env}}"
    loop: "{{Instances}}"
    register: ec2

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ec2}}"
    
  