# download py library botocore and boto3 becoz ansible develoed in python ;  in background python code will execute 
# pip3.9 install botocore boto3
- name : Instance and route53 creation
  hosts: all
  connection: local

  become: false
  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    SG_ID: "sg-0b1f7c3d25067bf9a"
    SUBNET_ID: "subnet-0bb417478919bf408"
    env: "dev"
    ZONE_ID: "Z07326442Z8C3IRLJ3030"
    DOMAIN_NAME: "cloudkarna.in"

    Instances:
      - dynamodb
      - cart

  tasks:
  - name: Instance creation
    amazon.aws.ec2_instance: 
      instance_type: "t3.micro"
      image_id: "{{ ami_id }}"
      region: "us-east-1"
      security_group: "{{SG_ID}}"
      vpc_subnet_id: "{{SUBNET_ID}}"
      tags:
        Name: "{{ item }}-{{ env }}"
        project: roboshop
        component: "{{ item }}"
        Environment: "{{ env }}"
        
    loop: "{{ Instances }}"
    register: ec2

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2 }}"
    
  

  
  - name: create route53
    amazon.aws.route53:
      state: present
      zone: "{{ DOMAIN_NAME }}" # cloudkarna.in
      record: "{{ item.item }}-{{ env }}.{{ DOMAIN_NAME }}" #mongodb-dev.cloudkarna.in
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}" #first entry inside instance oth position and get private IP
      register: a_record_change
    

  - name: Print summary
    ansible.builtin.debug:
      msg: "Created {{ item.item }}-{{ env }} => {{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2.results }}"